apiVersion: apps/v1
kind: Deployment
metadata:
  name: visa.api.connector-v2-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: visa-api-connector-v2
  template:
    metadata:
      labels:
        app: visa-api-connector-v2
    spec:
      containers:
        - name: visa-api-connector-v2
          image: jayasanka/visa-api-connector-v2:1.0
          imagePullPolicy: Always
          env:
            - name: SPRING_VISA_CLIENT_SSL_TRUST_STORE
              value: /var/local/certs/visaApiConnector_keyAndCertBundle.jks
          volumeMounts:
            - name: logs-dir-volume
              mountPath: /var/local/logs
            - name: certs-file-volume
              mountPath: /var/local/certs/visaApiConnector_keyAndCertBundle.jks
              subPath: visaApiConnector_keyAndCertBundle.jks
          command: ["/bin/sh", "-c", "ls -la /var/local/certs/"]
#          args: ["ls -la /var/local/certs/", cp -R /var/local/certs/* /data/certs/"]
      volumes:
        - name: certs-dir-volume
          hostPath:
            path: /var/local/certs
            type: DirectoryOrCreate
        - name: certs-file-volume
          hostPath:
            path: /var/local/certs/visaApiConnector_keyAndCertBundle.jks
            type: File
        - name: logs-dir-volume
          emptyDir: {}
              