apiVersion: apps/v1
kind: Deployment
metadata:
  name: visa.api.connector-v2-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: visa-api-connector-v2
  template:
    metadata:
      labels:
        app: visa-api-connector-v2
    spec:
      containers:
        - name: visa-api-connector-v2
          image: jayasanka/visa-api-connector-v2:1.0
          env:
            - name: SPRING_VISA_CLIENT_SSL_TRUST_STORE
              value: /data/certs/visaApiConnector_keyAndCertBundle.jks
          volumeMounts:
            - name: certs-volume
              mountPath: /data/certs
            - name: certs
              mountPath: /data/certs/visaApiConnector_keyAndCertBundle.jks
              subPath: visaApiConnector_keyAndCertBundle.jks
            - name: logs-volume
              mountPath: /data/logs
      volumes:
        - name: certs-volume
          hostPath:
            path: /data/certs/
            type: DirectoryOrCreate
        - name: certs
          hostPath:
            path: /data/certs/visaApiConnector_keyAndCertBundle.jks
            type: File
        - name: logs-volume
          hostPath:
            path: /data/logs
            type: DirectoryOrCreate