apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: visa-api-connector-v2-persistent-volume-claim
  labels:
    app: visa-api-connector-v2
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: slow