apiVersion: v1
kind: PersistentVolume
metadata:
  name: visa-api-connector-v2-persistent-volume
  labels:
    type: local
    app: visa-api-connector-v2
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/data/certs"