apiVersion: v1
kind: Service
metadata:
  name: visa-api-connector-v2-service
spec:
  selector:
    app: visa-api-connector-v2
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  clusterIP: 10.96.10.20
status:
  loadBalancer:
    ingress:
    - ip: 192.0.2.127