apiVersion: v1
kind: Service
metadata:
  name: visa-api-connector-v2-service
spec:
  selector:
    app: visa-api-connector-v2
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
